//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientFlightWS.FlightWS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://javabegin.ru/training/ws")]
    public partial class ArgumentException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private exceptionInfo exceptionInfoField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public exceptionInfo exceptionInfo {
            get {
                return this.exceptionInfoField;
            }
            set {
                this.exceptionInfoField = value;
                this.RaisePropertyChanged("exceptionInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://javabegin.ru/training/ws")]
    public partial class exceptionInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string traceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string trace {
            get {
                return this.traceField;
            }
            set {
                this.traceField = value;
                this.RaisePropertyChanged("trace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://javabegin.ru/training/ws")]
    public partial class flightClass : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descField;
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://javabegin.ru/training/ws")]
    public partial class place : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string seatLetterField;
        
        private int seatNumberField;
        
        private flightClass flightClassField;
        
        private bool busyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string seatLetter {
            get {
                return this.seatLetterField;
            }
            set {
                this.seatLetterField = value;
                this.RaisePropertyChanged("seatLetter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int seatNumber {
            get {
                return this.seatNumberField;
            }
            set {
                this.seatNumberField = value;
                this.RaisePropertyChanged("seatNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public flightClass flightClass {
            get {
                return this.flightClassField;
            }
            set {
                this.flightClassField = value;
                this.RaisePropertyChanged("flightClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool busy {
            get {
                return this.busyField;
            }
            set {
                this.busyField = value;
                this.RaisePropertyChanged("busy");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://javabegin.ru/training/ws")]
    public partial class company : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descField;
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://javabegin.ru/training/ws")]
    public partial class aircraft : object, System.ComponentModel.INotifyPropertyChanged {
        
        private company companyField;
        
        private string descField;
        
        private place[] freePlaceListField;
        
        private long idField;
        
        private string nameField;
        
        private place[] placeListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public company company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("freePlaceList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public place[] freePlaceList {
            get {
                return this.freePlaceListField;
            }
            set {
                this.freePlaceListField = value;
                this.RaisePropertyChanged("freePlaceList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("placeList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public place[] placeList {
            get {
                return this.placeListField;
            }
            set {
                this.placeListField = value;
                this.RaisePropertyChanged("placeList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://javabegin.ru/training/ws")]
    public partial class flight : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string durationField;
        
        private bool existFreePlacesField;
        
        private bool existFreePlacesFieldSpecified;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string codeField;
        
        private System.DateTime dateDepartField;
        
        private System.DateTime dateComeField;
        
        private bool dateComeFieldSpecified;
        
        private aircraft aircraftField;
        
        private city cityFromField;
        
        private city cityToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
                this.RaisePropertyChanged("duration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool existFreePlaces {
            get {
                return this.existFreePlacesField;
            }
            set {
                this.existFreePlacesField = value;
                this.RaisePropertyChanged("existFreePlaces");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool existFreePlacesSpecified {
            get {
                return this.existFreePlacesFieldSpecified;
            }
            set {
                this.existFreePlacesFieldSpecified = value;
                this.RaisePropertyChanged("existFreePlacesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime dateDepart {
            get {
                return this.dateDepartField;
            }
            set {
                this.dateDepartField = value;
                this.RaisePropertyChanged("dateDepart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime dateCome {
            get {
                return this.dateComeField;
            }
            set {
                this.dateComeField = value;
                this.RaisePropertyChanged("dateCome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateComeSpecified {
            get {
                return this.dateComeFieldSpecified;
            }
            set {
                this.dateComeFieldSpecified = value;
                this.RaisePropertyChanged("dateComeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public aircraft aircraft {
            get {
                return this.aircraftField;
            }
            set {
                this.aircraftField = value;
                this.RaisePropertyChanged("aircraft");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public city cityFrom {
            get {
                return this.cityFromField;
            }
            set {
                this.cityFromField = value;
                this.RaisePropertyChanged("cityFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public city cityTo {
            get {
                return this.cityToField;
            }
            set {
                this.cityToField = value;
                this.RaisePropertyChanged("cityTo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://javabegin.ru/training/ws")]
    public partial class city : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string nameField;
        
        private string descField;
        
        private country countryField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public country country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://javabegin.ru/training/ws")]
    public partial class country : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descField;
        
        private byte[] flagField;
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
                this.RaisePropertyChanged("desc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
        public byte[] flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
                this.RaisePropertyChanged("flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://javabegin.ru/training/ws", ConfigurationName="FlightWS.FlightWS")]
    public interface FlightWS {
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://javabegin.ru/training/ws/FlightWS/getAllCitiesRequest", ReplyAction="http://javabegin.ru/training/ws/FlightWS/getAllCitiesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientFlightWS.FlightWS.getAllCitiesResponse getAllCities(ClientFlightWS.FlightWS.getAllCitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://javabegin.ru/training/ws/FlightWS/getAllCitiesRequest", ReplyAction="http://javabegin.ru/training/ws/FlightWS/getAllCitiesResponse")]
        System.Threading.Tasks.Task<ClientFlightWS.FlightWS.getAllCitiesResponse> getAllCitiesAsync(ClientFlightWS.FlightWS.getAllCitiesRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://javabegin.ru/training/ws/FlightWS/searchFlightRequest", ReplyAction="http://javabegin.ru/training/ws/FlightWS/searchFlightResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientFlightWS.FlightWS.ArgumentException), Action="http://javabegin.ru/training/ws/FlightWS/searchFlight/Fault/ArgumentException", Name="ArgumentException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientFlightWS.FlightWS.searchFlightResponse searchFlight(ClientFlightWS.FlightWS.searchFlightRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://javabegin.ru/training/ws/FlightWS/searchFlightRequest", ReplyAction="http://javabegin.ru/training/ws/FlightWS/searchFlightResponse")]
        System.Threading.Tasks.Task<ClientFlightWS.FlightWS.searchFlightResponse> searchFlightAsync(ClientFlightWS.FlightWS.searchFlightRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://javabegin.ru/training/ws/FlightWS/buyTicketRequest", ReplyAction="http://javabegin.ru/training/ws/FlightWS/buyTicketResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientFlightWS.FlightWS.ArgumentException), Action="http://javabegin.ru/training/ws/FlightWS/buyTicket/Fault/ArgumentException", Name="ArgumentException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientFlightWS.FlightWS.buyTicketResponse buyTicket(ClientFlightWS.FlightWS.buyTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://javabegin.ru/training/ws/FlightWS/buyTicketRequest", ReplyAction="http://javabegin.ru/training/ws/FlightWS/buyTicketResponse")]
        System.Threading.Tasks.Task<ClientFlightWS.FlightWS.buyTicketResponse> buyTicketAsync(ClientFlightWS.FlightWS.buyTicketRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://javabegin.ru/training/ws/FlightWS/checkReservationByCodeRequest", ReplyAction="http://javabegin.ru/training/ws/FlightWS/checkReservationByCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientFlightWS.FlightWS.ArgumentException), Action="http://javabegin.ru/training/ws/FlightWS/checkReservationByCode/Fault/ArgumentExc" +
            "eption", Name="ArgumentException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClientFlightWS.FlightWS.checkReservationByCodeResponse checkReservationByCode(ClientFlightWS.FlightWS.checkReservationByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://javabegin.ru/training/ws/FlightWS/checkReservationByCodeRequest", ReplyAction="http://javabegin.ru/training/ws/FlightWS/checkReservationByCodeResponse")]
        System.Threading.Tasks.Task<ClientFlightWS.FlightWS.checkReservationByCodeResponse> checkReservationByCodeAsync(ClientFlightWS.FlightWS.checkReservationByCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllCities", WrapperNamespace="http://javabegin.ru/training/ws", IsWrapped=true)]
    public partial class getAllCitiesRequest {
        
        public getAllCitiesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllCitiesResponse", WrapperNamespace="http://javabegin.ru/training/ws", IsWrapped=true)]
    public partial class getAllCitiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://javabegin.ru/training/ws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientFlightWS.FlightWS.city[] @return;
        
        public getAllCitiesResponse() {
        }
        
        public getAllCitiesResponse(ClientFlightWS.FlightWS.city[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchFlight", WrapperNamespace="http://javabegin.ru/training/ws", IsWrapped=true)]
    public partial class searchFlightRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://javabegin.ru/training/ws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://javabegin.ru/training/ws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientFlightWS.FlightWS.city cityFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://javabegin.ru/training/ws", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientFlightWS.FlightWS.city cityTo;
        
        public searchFlightRequest() {
        }
        
        public searchFlightRequest(long date, ClientFlightWS.FlightWS.city cityFrom, ClientFlightWS.FlightWS.city cityTo) {
            this.date = date;
            this.cityFrom = cityFrom;
            this.cityTo = cityTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchFlightResponse", WrapperNamespace="http://javabegin.ru/training/ws", IsWrapped=true)]
    public partial class searchFlightResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://javabegin.ru/training/ws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientFlightWS.FlightWS.flight[] @return;
        
        public searchFlightResponse() {
        }
        
        public searchFlightResponse(ClientFlightWS.FlightWS.flight[] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://javabegin.ru/training/ws")]
    public partial class passenger : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string givenNameField;
        
        private string middleNameField;
        
        private string familyNameField;
        
        private string documentNumberField;
        
        private string emailField;
        
        private string phoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string givenName {
            get {
                return this.givenNameField;
            }
            set {
                this.givenNameField = value;
                this.RaisePropertyChanged("givenName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string middleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
                this.RaisePropertyChanged("middleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string familyName {
            get {
                return this.familyNameField;
            }
            set {
                this.familyNameField = value;
                this.RaisePropertyChanged("familyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string documentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
                this.RaisePropertyChanged("documentNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("phone");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buyTicket", WrapperNamespace="http://javabegin.ru/training/ws", IsWrapped=true)]
    public partial class buyTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://javabegin.ru/training/ws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long flightId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://javabegin.ru/training/ws", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long placeId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://javabegin.ru/training/ws", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientFlightWS.FlightWS.passenger passenger;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://javabegin.ru/training/ws", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string addInfo;
        
        public buyTicketRequest() {
        }
        
        public buyTicketRequest(long flightId, long placeId, ClientFlightWS.FlightWS.passenger passenger, string addInfo) {
            this.flightId = flightId;
            this.placeId = placeId;
            this.passenger = passenger;
            this.addInfo = addInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buyTicketResponse", WrapperNamespace="http://javabegin.ru/training/ws", IsWrapped=true)]
    public partial class buyTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://javabegin.ru/training/ws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public buyTicketResponse() {
        }
        
        public buyTicketResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://javabegin.ru/training/ws")]
    public partial class reservation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private flight flightField;
        
        private passenger passengerField;
        
        private place placeField;
        
        private string addInfoField;
        
        private System.DateTime reserveDateTimeField;
        
        private bool reserveDateTimeFieldSpecified;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public flight flight {
            get {
                return this.flightField;
            }
            set {
                this.flightField = value;
                this.RaisePropertyChanged("flight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public passenger passenger {
            get {
                return this.passengerField;
            }
            set {
                this.passengerField = value;
                this.RaisePropertyChanged("passenger");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public place place {
            get {
                return this.placeField;
            }
            set {
                this.placeField = value;
                this.RaisePropertyChanged("place");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string addInfo {
            get {
                return this.addInfoField;
            }
            set {
                this.addInfoField = value;
                this.RaisePropertyChanged("addInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime reserveDateTime {
            get {
                return this.reserveDateTimeField;
            }
            set {
                this.reserveDateTimeField = value;
                this.RaisePropertyChanged("reserveDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reserveDateTimeSpecified {
            get {
                return this.reserveDateTimeFieldSpecified;
            }
            set {
                this.reserveDateTimeFieldSpecified = value;
                this.RaisePropertyChanged("reserveDateTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkReservationByCode", WrapperNamespace="http://javabegin.ru/training/ws", IsWrapped=true)]
    public partial class checkReservationByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://javabegin.ru/training/ws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code;
        
        public checkReservationByCodeRequest() {
        }
        
        public checkReservationByCodeRequest(string code) {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkReservationByCodeResponse", WrapperNamespace="http://javabegin.ru/training/ws", IsWrapped=true)]
    public partial class checkReservationByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://javabegin.ru/training/ws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClientFlightWS.FlightWS.reservation @return;
        
        public checkReservationByCodeResponse() {
        }
        
        public checkReservationByCodeResponse(ClientFlightWS.FlightWS.reservation @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FlightWSChannel : ClientFlightWS.FlightWS.FlightWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FlightWSClient : System.ServiceModel.ClientBase<ClientFlightWS.FlightWS.FlightWS>, ClientFlightWS.FlightWS.FlightWS {
        
        public FlightWSClient() {
        }
        
        public FlightWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FlightWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlightWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlightWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientFlightWS.FlightWS.getAllCitiesResponse ClientFlightWS.FlightWS.FlightWS.getAllCities(ClientFlightWS.FlightWS.getAllCitiesRequest request) {
            return base.Channel.getAllCities(request);
        }
        
        public ClientFlightWS.FlightWS.city[] getAllCities() {
            ClientFlightWS.FlightWS.getAllCitiesRequest inValue = new ClientFlightWS.FlightWS.getAllCitiesRequest();
            ClientFlightWS.FlightWS.getAllCitiesResponse retVal = ((ClientFlightWS.FlightWS.FlightWS)(this)).getAllCities(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientFlightWS.FlightWS.getAllCitiesResponse> ClientFlightWS.FlightWS.FlightWS.getAllCitiesAsync(ClientFlightWS.FlightWS.getAllCitiesRequest request) {
            return base.Channel.getAllCitiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientFlightWS.FlightWS.getAllCitiesResponse> getAllCitiesAsync() {
            ClientFlightWS.FlightWS.getAllCitiesRequest inValue = new ClientFlightWS.FlightWS.getAllCitiesRequest();
            return ((ClientFlightWS.FlightWS.FlightWS)(this)).getAllCitiesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientFlightWS.FlightWS.searchFlightResponse ClientFlightWS.FlightWS.FlightWS.searchFlight(ClientFlightWS.FlightWS.searchFlightRequest request) {
            return base.Channel.searchFlight(request);
        }
        
        public ClientFlightWS.FlightWS.flight[] searchFlight(long date, ClientFlightWS.FlightWS.city cityFrom, ClientFlightWS.FlightWS.city cityTo) {
            ClientFlightWS.FlightWS.searchFlightRequest inValue = new ClientFlightWS.FlightWS.searchFlightRequest();
            inValue.date = date;
            inValue.cityFrom = cityFrom;
            inValue.cityTo = cityTo;
            ClientFlightWS.FlightWS.searchFlightResponse retVal = ((ClientFlightWS.FlightWS.FlightWS)(this)).searchFlight(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientFlightWS.FlightWS.searchFlightResponse> ClientFlightWS.FlightWS.FlightWS.searchFlightAsync(ClientFlightWS.FlightWS.searchFlightRequest request) {
            return base.Channel.searchFlightAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientFlightWS.FlightWS.searchFlightResponse> searchFlightAsync(long date, ClientFlightWS.FlightWS.city cityFrom, ClientFlightWS.FlightWS.city cityTo) {
            ClientFlightWS.FlightWS.searchFlightRequest inValue = new ClientFlightWS.FlightWS.searchFlightRequest();
            inValue.date = date;
            inValue.cityFrom = cityFrom;
            inValue.cityTo = cityTo;
            return ((ClientFlightWS.FlightWS.FlightWS)(this)).searchFlightAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientFlightWS.FlightWS.buyTicketResponse ClientFlightWS.FlightWS.FlightWS.buyTicket(ClientFlightWS.FlightWS.buyTicketRequest request) {
            return base.Channel.buyTicket(request);
        }
        
        public bool buyTicket(long flightId, long placeId, ClientFlightWS.FlightWS.passenger passenger, string addInfo) {
            ClientFlightWS.FlightWS.buyTicketRequest inValue = new ClientFlightWS.FlightWS.buyTicketRequest();
            inValue.flightId = flightId;
            inValue.placeId = placeId;
            inValue.passenger = passenger;
            inValue.addInfo = addInfo;
            ClientFlightWS.FlightWS.buyTicketResponse retVal = ((ClientFlightWS.FlightWS.FlightWS)(this)).buyTicket(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientFlightWS.FlightWS.buyTicketResponse> ClientFlightWS.FlightWS.FlightWS.buyTicketAsync(ClientFlightWS.FlightWS.buyTicketRequest request) {
            return base.Channel.buyTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientFlightWS.FlightWS.buyTicketResponse> buyTicketAsync(long flightId, long placeId, ClientFlightWS.FlightWS.passenger passenger, string addInfo) {
            ClientFlightWS.FlightWS.buyTicketRequest inValue = new ClientFlightWS.FlightWS.buyTicketRequest();
            inValue.flightId = flightId;
            inValue.placeId = placeId;
            inValue.passenger = passenger;
            inValue.addInfo = addInfo;
            return ((ClientFlightWS.FlightWS.FlightWS)(this)).buyTicketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientFlightWS.FlightWS.checkReservationByCodeResponse ClientFlightWS.FlightWS.FlightWS.checkReservationByCode(ClientFlightWS.FlightWS.checkReservationByCodeRequest request) {
            return base.Channel.checkReservationByCode(request);
        }
        
        public ClientFlightWS.FlightWS.reservation checkReservationByCode(string code) {
            ClientFlightWS.FlightWS.checkReservationByCodeRequest inValue = new ClientFlightWS.FlightWS.checkReservationByCodeRequest();
            inValue.code = code;
            ClientFlightWS.FlightWS.checkReservationByCodeResponse retVal = ((ClientFlightWS.FlightWS.FlightWS)(this)).checkReservationByCode(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientFlightWS.FlightWS.checkReservationByCodeResponse> ClientFlightWS.FlightWS.FlightWS.checkReservationByCodeAsync(ClientFlightWS.FlightWS.checkReservationByCodeRequest request) {
            return base.Channel.checkReservationByCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientFlightWS.FlightWS.checkReservationByCodeResponse> checkReservationByCodeAsync(string code) {
            ClientFlightWS.FlightWS.checkReservationByCodeRequest inValue = new ClientFlightWS.FlightWS.checkReservationByCodeRequest();
            inValue.code = code;
            return ((ClientFlightWS.FlightWS.FlightWS)(this)).checkReservationByCodeAsync(inValue);
        }
    }
}
